steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/cvfactory-server:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/cvfactory-server:$COMMIT_SHA']
- name: 'gcr.io/google-cloud-sdk/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'cvfactory-server'
  - '--image'
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/cvfactory-server:$COMMIT_SHA'
  - '--region'
  - 'asia-northeast3'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
- 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/cvfactory-server:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY 