steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/cvfactory-server:$COMMIT_SHA'
    - '.'
  id: 'Build Docker image'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/cvfactory-server:$COMMIT_SHA'
  id: 'Push to Artifact Registry'
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'cvfactory-server'
    - '--image'
    - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/cvfactory-server:$COMMIT_SHA'
    - '--region'
    - 'asia-northeast3'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--remove-env-vars=REDIS_URL'
    - '--update-secrets=REDIS_URL=REDIS_URL_FOR_RUN:latest'
images:
- 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/cvfactory-server:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY 