steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cvfactory/cvfactory-server:latest', '.']
# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cvfactory/cvfactory-server:latest']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud run deploy cvfactory-server \
        --image asia-northeast3-docker.pkg.dev/$PROJECT_ID/cvfactory/cvfactory-server:latest \
        --region asia-northeast3 \
        --platform managed \
        --allow-unauthenticated \
        --port 8000 \
        --cpu 1 \
        --memory 2Gi \
        --min-instances 0 \
        --max-instances 1 \
        --set-env-vars="PYTHONUNBUFFERED=1,REDIS_URL=redis://localhost:6379/0" \
        --update-secrets=GEMINI_API_KEY=GEMINI_API_KEY:latest,COHERE_API_KEY=COHERE_API_KEY:latest # GEMINI_API_KEY와 COHERE_API_KEY 시크릿 사용
images:
- 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cvfactory/cvfactory-server:latest'
options:
  logging: CLOUD_LOGGING_ONLY 