version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    command: ["./entrypoint.sh", "web"]

  worker:
    build: .
    volumes:
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    command: ["./entrypoint.sh", "worker"]

volumes: 