version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: my-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
    restart: always

  web:
    build: .
    container_name: cvfactory_web
    ports:
      - "8000:8080"
    environment:
      REDIS_URL: redis://redis:6379/0
    entrypoint: ["/app/entrypoint.sh", "web"]
    depends_on:
      - redis
    restart: always

  worker:
    build: .
    container_name: cvfactory_worker
    environment:
      REDIS_URL: redis://redis:6379/0
    entrypoint: ["/app/entrypoint.sh", "worker"]
    depends_on:
      - redis
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - ./logs:/app/logs

volumes:
  redisdata: 